controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

upload_image:
    path: /upload-image
    controller: App\Controller\ImageController::uploadImage
    methods: [POST]